### PR TITLE
donations: Improve wording on becoming a patron

### PR DESCRIPTION
**Pull request by the-j0k3r**
- [x] The commit message follows the rest of the commits and passes the post-commit test
- [ ] If you've introduced a new feature, you also wrote tests for it and they all pass

## New behaviour:  

Improve wording, just like Paypal this is implied so the preposition `on` is superfluous.

Before
screenshot-2018-6-12 openusercss 2

After
screenshot-2018-6-12 openusercss 3

### CODE REVIEW

**Comment by DecentM** [comment]
Thank you for the PR!  

I wrote them this way to make it sound like the logos are part of the expression. If we're to change this text, I think the PayPal one should be different as well.  
Can you propose a change for that one too, without making it just one word?

**Comment by the-j0k3r** [comment]
>I wrote them this way to make it sound like the logos are part of the expression

I realized that, which is actually a mouth/thought full -Become a patron on patreon.

At this very moment aside from **Donate now** [PP] only **Support us** [PP] comes to mind, IDK keeping it succinct seems better.

**Comment by DecentM** [comment]
On second thought, maybe it's a good idea to change this right side.  
I think it'd be better if it was a full sentence, so if you could change it to add an exclamation mark at the end, I don't think there'd be a reason not to merge :+1:

**Comment by DecentM** [comment]
The guidelines you posted are pretty much the only one I can find that describes the situation clearly. However, it applies to cobranding, which is when two brands partner. Outside of their TOS, I don't have any partnership with them, so I don't believe this applies.  

That said, I'd like to voluntarily comply with what this doc asks for, so I'll merge this if you can put an exclamation mark at the end. You can also take care of the PayPal text if you want, up to you :+1:

**Comment by the-j0k3r** [comment]
Exclamation mark where?

**Comment by DecentM** [comment]
I was thinking like 'Become a Patron!'

**Comment by the-j0k3r** [comment]
OK I guess. What About the PayPal text, How about <kbd>Donate now!</kbd>

**Comment by the-j0k3r** [comment]
Have a look-see captain :0

**Comment by DecentM** [comment]
Sorry for being picky, I think `Donate!` is enough, I don't want it to sound super desperate :laughing:  

> ...a better way to ensure people went through...  

I later want to develop some extra features and tie them to it, but it's not a huge priority for now.

**Comment by the-j0k3r** [comment]
You mean super desperate!

**Pull request merged**
