### PR TITLE
contributing.md: fix typos

### PR DESCRIPTION
**Pull request by the-j0k3r**
- [ ] The commit message follows the rest of the commits and passes the post-commit test
- [ ] If you've introduced a new feature, you also wrote tests for it and they all pass

## TL;DR:  

Fixes typos in CONTRIBUTING.md

fulfills -> fulfils
oterwise -> otherwise

### CODE REVIEW

**Comment by hyperfekt** [comment]
Acshually, fulfills is also correct and the US spelling.

**Comment by the-j0k3r** [comment]
US spelling? Is that a standard for anything?

**Comment by hyperfekt** [comment]
? Standard? I'm not aware of any standards body for the English language.
It's in both the Oxford dictionary and Merriam-Webster, which is probably the closest thing.
I am not saying _fulfil_ is incorrect, just that the other form is not a typo.
Which one to choose depends both on the form of spelling used for other words and if one gives a fuck.

**Comment by the-j0k3r** [comment]
I invoke dealers choice.

One corrected and one changed.

**Comment by DecentM** [comment]
Thanks for the PR!  
If you can rewrite the commit message to be `fix(docs): Correct typos`, I can merge this faster, or if you don't want to, I can do that tomorrow later as well :+1:

**Comment by the-j0k3r** [comment]
> you can rewrite the commit message to be fix(docs): Correct typos, I can merge this faster

Aye aye Cpt. done.

**Comment by DecentM** [comment]
Merged, thanks again!

**Pull request merged**
